#!/usr/bin/env python
# git show in vim
from os import makedirs as mkdir_p,system as x, chdir as cd
from os.path import join as j, dirname as dn
import re
from shutil import rmtree as rm_r
from subprocess import check_output as co
from sys import argv
from tempfile import mkdtemp

_=lambda cmd:co(cmd.format(**globals()).split())

def write(p,c):
  with open(p,'w') as f:
    f.write(c.encode('utf8'))

if len(argv) > 1:
  r=argv[1]
else:
  r='HEAD'

d=mkdtemp(prefix='gitv')
dif=_('git show {r}')

# write commit msg
ss=re.split('(?m)(^diff --git.*)',dif)
msg=ss[0]
write(j(d,'COMMIT_EDITMSG'),msg)

# write separate file diffs
for i in xrange(1,len(ss),2):
  hd=ss[i]
  dd=ss[i+1]
  p=hd.split()[2][2:]+'.patch'
  try:
    mkdir_p(dn(j(d,p)))
  except:
    pass
  write(j(d,p),hd+dd)

cd(d)
x('vim `find . -type f`')
rm_r(d)
