#!/usr/bin/env python
from sys import stdin

prev=''
for line in stdin:
  line=line.strip()
  if not line or line.startswith('#'):
    continue

  words=line.split()
  hash=words[1]
  date= ' '.join(words[4:7])

  if date==prev:
    print 'f',hash,' '.join(words[2:])
  else:
    print 'r',hash,' '.join(words[2:])
    prev=date
